/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LOGINS;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jComboBox6 = new javax.swing.JComboBox<String>();
        jComboBox7 = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(200, 17, 27));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOKINGS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(132, 11, 549, 66);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" NAME :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 95, 81, 41);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(109, 97, 222, 41);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FROM :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 205, 50, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MUMBAI", "DELHI", "PUNE", "BANGLORE", "GUJRAT" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 200, 78, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TO :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(467, 194, 47, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MUMBAI", "DELHI", "PUNE", "BANGLORE", "GUJRAT" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(629, 194, 88, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DEPARTURE TIMING:-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 277, 135, 17);

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(163, 277, 86, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ARRIVING TIME :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 280, 108, 17);

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(630, 280, 88, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(280, 200, 92, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(791, 194, 98, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(295, 277, 92, 20);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(791, 280, 98, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date :-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(777, 353, 43, 17);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jan", "feb", "mar", "apr", "jun", "jul", "aug", "sep", "oct", "nov", "dec" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(952, 353, 70, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(860, 353, 50, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021", "2022" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(1048, 353, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adults");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(82, 402, 37, 17);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(114, 430, 40, 20);

        jButton1.setText("GET SET GO..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(295, 492, 205, 65);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Children");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(231, 402, 49, 17);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox9);
        jComboBox9.setBounds(231, 430, 40, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Infant");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(382, 402, 36, 17);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));
        getContentPane().add(jComboBox10);
        jComboBox10.setBounds(382, 430, 40, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Class :-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(602, 415, 50, 35);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUSINESS", "ECONOMIC" }));
        getContentPane().add(jComboBox11);
        jComboBox11.setBounds(656, 417, 104, 35);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("E-MAIL :-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(416, 107, 56, 17);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(511, 95, 249, 35);

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(82, 492, 90, 30);

        jLabel13.setBackground(new java.awt.Color(51, 255, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmcproject/hwtiEcD-aircraft-wallpaper-hd.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 10, 1690, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String sdd = (String) jComboBox1.getSelectedItem();
        jTextField2.setText(sdd);
        jTextField2.setEditable(false);
        if (sdd.equals("MUMBAI")) {
            jComboBox3.removeAllItems();
             jComboBox4.removeAllItems();
            jComboBox3.addItem("11:30am");
            jComboBox3.addItem("2:00pm");
            jComboBox3.addItem("4:00pm");
        }
        if (sdd.equals("DELHI")) {
            jComboBox3.removeAllItems();
            jComboBox4.removeAllItems();
            jComboBox3.addItem("7:30am");
            jComboBox3.addItem("10:30am");
            jComboBox3.addItem("1:00pm");
        }
        if (sdd.equals("PUNE")) {
            jComboBox3.removeAllItems();
            jComboBox4.removeAllItems();
            jComboBox3.addItem("7:20am");
            jComboBox3.addItem("10:10am");
            jComboBox3.addItem("1:50pm");
        }

        if (sdd.equals("BANGLORE")) {
            jComboBox3.removeAllItems();
            jComboBox4.removeAllItems();
            jComboBox3.addItem("9:30am");
            jComboBox3.addItem("12:30pm");
            jComboBox3.addItem("3:00pm");
        }
        if (sdd.equals("GUJRAT")) {
            jComboBox3.removeAllItems();
            jComboBox4.removeAllItems();
            jComboBox3.addItem("8:10am");
            jComboBox3.addItem("11:10am");
            jComboBox3.addItem("2:10pm");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        String s = (String) jComboBox3.getSelectedItem();
        jTextField4.setText(s);
        jTextField4.setEditable(false);
        // TODO add your handling code here:
        if (s.equals("11:30am")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("1:30pm");

        }
        
        if (s.equals("2:00pm")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("4:00pm");

        }
        if (s.equals("4:00pm")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("6:00pm");

        }
       

        if (s.equals("7:30am")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("9:30am");

        }
        if (s.equals("10:30am")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("12:10pm");

        }
        if (s.equals("1:00pm")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("3:00pm");

        }
        if (s.equals("7:20am")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("9:20am");

        }
        if (s.equals("10:10am")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("1:10pm");

        }
        if (s.equals("1:50pm")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("3:00pm");

        }
        if (s.equals("9:30am")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("11:20am");

        }
        if (s.equals("12:30pm")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("2:10pm");

        }
        if (s.equals("3:00pm")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("5:50pm");

        }
        if (s.equals("8:10am")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("10:00am");

        }
        if (s.equals("11:10am")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("1:30pm");

        }
        if (s.equals("2:10pm")) {
            jComboBox4.removeAllItems();

            jComboBox4.addItem("4:10pm");

        }
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String sdd = (String) jComboBox2.getSelectedItem();
        jTextField3.setText(sdd);
        jTextField3.setEditable(false);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
String s = (String) jComboBox4.getSelectedItem();
        jTextField5.setText(s);
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField2.setText(null);
jTextField4.setText(null);
jTextField3.setText(null);
jTextField5.setText(null);
String s="";
jComboBox1.setSelectedItem(s);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String adult,children,infant,clas;
      adult=(String)jComboBox8.getSelectedItem();
      children=(String)jComboBox9.getSelectedItem();
      infant=(String)jComboBox10.getSelectedItem();
      clas=(String)jComboBox11.getSelectedItem();
        
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
          Connection  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","system");
          System.out.println(con);
            PreparedStatement pst=con.prepareStatement("insert into BOOKINGS values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, jTextField1.getText());
            pst.setString(2,jTextField6.getText());
            pst.setString(3,jTextField2.getText());
            pst.setString(4,jTextField3.getText());
            pst.setString(5,jTextField4.getText());
            pst.setString(6,jTextField5.getText());
            pst.setString(7,adult);
            pst.setString(8,children);
            pst.setString(9,infant);
            pst.setString(10,clas);
                                            
           int i=pst.executeUpdate();
           if(i==1)
           {
               JOptionPane.showMessageDialog(null, "connecting to payment page");
           }
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
